name: MD_lab
channels:
 - defaults
 - conda-forge
 - ambermd
 - omnia
dependencies:
 - python>=3.6
 - pip
 - pytest
 - jupyterlab
 - nodejs
 - yarn
 - ipywidgets==7.*
 - matplotlib
 - numpy
 - mdtraj
 - nglview
 - scipy
 - pandas
 - brewer2mpl
 - notebook
 - vim
 - jupyter
 - eigen
 - parmed
 - openmp
 - gfortran_linux-64
 - gcc_linux-64
